### ISSUE TITLE
Update NetworkObject to sync objects into SceneTree 

### ISSUE THREAD

**Issue by rdg922** [loudsmilestudios/TetraForce#113] opened 2020-08-14 04:34 UTC
### Sync objects not already in SceneTree
Currently, nodes not saved to the tilemap (such as dropped collectables) will not appear for players who enters into the map after the spawn of the node. Update NetworkObject to make peers send this data to new peers who enter a map.

**Comment by Nodding** [comment] 2021-07-28 00:00
duplicate of #248

**Closed by Nodding** 2021-07-28 00:00 UTC
Labels: bug
